// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5g5nxonJ9zko0mITP2pXwamNUk05eRNI',
    appId: '1:986514507040:web:ed231d78fe73b702180345',
    messagingSenderId: '986514507040',
    projectId: 'pineapple-tok-12340717',
    authDomain: 'pineapple-tok-12340717.firebaseapp.com',
    storageBucket: 'pineapple-tok-12340717.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ukq5sxDimoe5G5iDyrT9ffxZjtUxLLs',
    appId: '1:986514507040:android:012af30c5087ca46180345',
    messagingSenderId: '986514507040',
    projectId: 'pineapple-tok-12340717',
    storageBucket: 'pineapple-tok-12340717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHLdWQGSQp_CwNO4jHej69r6O8N7_ub-M',
    appId: '1:986514507040:ios:7cf9516609fbf162180345',
    messagingSenderId: '986514507040',
    projectId: 'pineapple-tok-12340717',
    storageBucket: 'pineapple-tok-12340717.appspot.com',
    iosClientId: '986514507040-qlr2o64i6nknvjj6b7tluihsa4au1nq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pineappleTok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHLdWQGSQp_CwNO4jHej69r6O8N7_ub-M',
    appId: '1:986514507040:ios:7cf9516609fbf162180345',
    messagingSenderId: '986514507040',
    projectId: 'pineapple-tok-12340717',
    storageBucket: 'pineapple-tok-12340717.appspot.com',
    iosClientId: '986514507040-qlr2o64i6nknvjj6b7tluihsa4au1nq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pineappleTok',
  );
}
